all:
  hosts:
    libvirt01:
      ansible_port: 22
      ansible_ssh_private_key_file: ~/.ssh/tokdosirak_ed25519
      ansible_host: 192.168.199.41
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    libvirt02:
      ansible_port: 22
      ansible_user: tokdosirak
      ansible_ssh_private_key_file: ~/.ssh/tokdosirak_ed25519
      ansible_host: 192.168.199.42
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'